dist: trusty

notifications:
  email: false

language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6

install:
  - pip install tox-travis

script:
  - tox
